Repository raphw/byte-buddy, pull requests merged in 2018-08, with the labels that each got.

#509 Do not try to set timeout for VirtualMachine#attach when its 0
  byte-buddy-agent/src/main/java/net/bytebuddy/agent/VirtualMachine.java
Labels: bug

#514 Fix Duplicated Words and Typos
  partial/tutorial.partial.html
Labels: documentation

#525 Allow using element matchers on MethodCall invocation target
  byte-buddy-dep/src/main/java/net/bytebuddy/implementation/MethodCall.java
  byte-buddy-dep/src/test/java/net/bytebuddy/implementation/MethodCallTest.java
Labels: enhancement

#528 Support using MethodCall.onField with static fields from other classes
  byte-buddy-dep/src/main/java/net/bytebuddy/implementation/MethodCall.java
  byte-buddy-dep/src/test/java/net/bytebuddy/implementation/MethodCallTest.java
Labels: bug
