Repository raphw/byte-buddy, pull requests merged in 2019-05, with the labels that each got.

#646 Split up the MethodAppender factory for copying annotations
  byte-buddy-dep/src/main/java/net/bytebuddy/implementation/attribute/MethodAttributeAppender.java
  byte-buddy-dep/src/test/java/net/bytebuddy/implementation/attribute/MethodAttributeAppenderExplicitTest.java
Labels: enhancement

#651 Fix "Apache License, Version 2.0" spelling
  pom.xml
Labels: documentation

#653 Add OpenJ9 11 Travis build
  .travis.yml
  ci/install-jdk.sh
Labels: build
