Repository raphw/byte-buddy, pull requests merged in 2019-01, with the labels that each got.

#580 Fixed typos and updated links in README
  README.md
Labels: documentation

#589 Optimize toArray (#588)
  byte-buddy-dep/src/main/java/net/bytebuddy/agent/builder/AgentBuilder.java
  byte-buddy-dep/src/main/java/net/bytebuddy/build/Plugin.java
  byte-buddy-dep/src/main/java/net/bytebuddy/description/annotation/AnnotationDescription.java
  byte-buddy-dep/src/main/java/net/bytebuddy/dynamic/ClassFileLocator.java
  byte-buddy-dep/src/main/java/net/bytebuddy/dynamic/loading/ClassReloadingStrategy.java
  byte-buddy-dep/src/main/java/net/bytebuddy/implementation/InvokeDynamic.java
  byte-buddy-dep/src/main/java/net/bytebuddy/implementation/auxiliary/PrivilegedMemberLookupAction.java
  byte-buddy-dep/src/main/java/net/bytebuddy/implementation/bytecode/member/MethodInvocation.java
  byte-buddy-dep/src/test/java/net/bytebuddy/description/method/MethodListForLoadedTypesTest.java
  byte-buddy-dep/src/test/java/net/bytebuddy/description/type/AbstractTypeDescriptionTest.java
  byte-buddy-dep/src/test/java/net/bytebuddy/matcher/AbstractElementMatcherTest.java
  byte-buddy-dep/src/test/java/net/bytebuddy/pool/TypePoolDefaultGenericTypeListTest.java
  byte-buddy-dep/src/test/java/net/bytebuddy/pool/TypePoolDefaultLazyAnnotationListTest.java
  byte-buddy-dep/src/test/java/net/bytebuddy/pool/TypePoolDefaultLazyFieldListTest.java
  byte-buddy-dep/src/test/java/net/bytebuddy/pool/TypePoolDefaultLazyMethodListTest.java
  byte-buddy-dep/src/test/java/net/bytebuddy/pool/TypePoolDefaultLazyTypeListTest.java
  byte-buddy-dep/src/test/java/net/bytebuddy/test/utility/CustomHamcrestMatchers.java
  byte-buddy-gradle-plugin/src/main/java/net/bytebuddy/build/gradle/ClassLoaderResolver.java
  byte-buddy-maven-plugin/src/main/java/net/bytebuddy/build/maven/ClassLoaderResolver.java
Labels: performance

#591 duplicated operand in bitmask
  byte-buddy-dep/src/main/java/net/bytebuddy/description/modifier/ModifierContributor.java
Labels: bug
