Repository raphw/byte-buddy, pull requests merged in 2020-10, with the labels that each got.

#935 Fix typo in sophisticated
  partial/main.partial.html
  partial/tutorial.partial.html
Labels: documentation

#930 Issue #660
  byte-buddy-dep/src/main/java/net/bytebuddy/asm/Advice.java
  byte-buddy-dep/src/test/java/net/bytebuddy/asm/AdviceTest.java
Labels: enhancement

#958 Fixes #957 by allowing static interface methods to be used as bootstrap methods for dynamic constants
  byte-buddy-dep/src/main/java/net/bytebuddy/utility/JavaConstant.java
Labels: bug

#955 Fixes #954 by making the assignability check more correct
  byte-buddy-dep/src/main/java/net/bytebuddy/utility/JavaConstant.java
  byte-buddy-dep/src/test/java/net/bytebuddy/utility/JavaConstantDynamicTest.java
Labels: bug

#951 Returns the proper descriptor for field-mutating MethodHandle constants to fix #948
  byte-buddy-dep/src/main/java/net/bytebuddy/utility/JavaConstant.java
  byte-buddy-dep/src/test/java/net/bytebuddy/utility/JavaConstantMethodHandleTest.java
Labels: bug

#965 Fix class injection for legacy classloaders which use getPackage internally on JDK9+
  byte-buddy-dep/src/main/java/net/bytebuddy/dynamic/loading/ClassInjector.java
  byte-buddy-dep/src/test/java/net/bytebuddy/dynamic/loading/ClassInjectorUsingReflectionTest.java
  byte-buddy-dep/src/test/java/net/bytebuddy/test/utility/LegacyGetPackageClassLoader.java
Labels: enhancement

#962 Fixes #961 by handing JavaConstant case in FixedValue.value() method
  byte-buddy-dep/src/main/java/net/bytebuddy/implementation/FixedValue.java
Labels: enhancement
